name: 'Dotfiles Test'
description: 'Run smoke tests for dotfiles'
inputs:
  run_as:
    description: 'User to run commands as (e.g., "ci" for containerized workflows)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Post-installation tests
      env:
        RUN_AS: ${{ inputs.run_as }}
      shell: bash
      run: |

        echo $HOME
        echo $GITHUB_WORKSPACE

        ls -la $HOME
        echo "---------------------------"
        ls -la $GITHUB_WORKSPACE

        # Build command arguments
        TEST_ARGS=""
        if [ -n "$RUN_AS" ]; then
          TEST_ARGS="$TEST_ARGS --run-as $RUN_AS"
        fi
        
        # Run the test suite
        ${GITHUB_WORKSPACE}/test/post_install.test.sh $TEST_ARGS
