onboarding = false

[theme]
name = "dracula"
auto_switch = false

[theme.custom]
panel_bg = "reset"
accent = "#00ffff"

[keys]
prefix = "`"
detach = "prefix+d"
previous_agent = "prefix+ctrl+k"
next_agent = "prefix+ctrl+j"
focus_agent = "prefix+ctrl+1..9"
split_vertical = "prefix+|"
navigate_workspace_up = "k"
navigate_workspace_down = "j"
goto = "prefix+/"
rename_tab = "prefix+,"
rename_pane = "prefix+."

[[keys.command]]
key = "prefix+g"
type = "popup"
command = "lazygit"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+y"
type = "popup"
command = "yazi"
width = "70%"
height = "90%"

[[keys.command]]
key = "prefix+space"
type = "plugin_action"
command = "dantehemerson.last-tab.toggle"
description = "last tab"

[ui]
# Immediately with generated names.
prompt_new_tab_name = false
show_agent_labels_on_pane_borders = true
right_click_passthrough_modifier = "alt"

[ui.sound]
# Play sounds when agents change state in background workspaces
enabled = true

[experimental]
kitty_graphics = true
