#!/bin/bash

echo "       ______      _    __ _ _                   "
echo "       |  _  \    | |  / _(_) |                  "
echo "       | | | |___ | |_| |_ _| | ___  ___         "
echo "       | | | / _ \| __|  _| | |/ _ \/ __|        "
echo "       | |/ / (_) | |_| | | | |  __/\__ \        "
echo "       |___/ \___/ \__|_| |_|_|\___||___/        "
echo "                                                 "
echo "              ❤ Dante's dotfiles ❤              "
echo "                 @dantehemerson                  "
echo ""

echo 'Updating repositories ...'
sudo apt-get update -y
sudo apt-get upgrade -y

echo "Installing dnsutils..."
sudo apt-get install dnsutils

echo "Installing git ..."
sudo apt-get install git -y

echo "Installing xclip ..."
sudo apt-get install xclip -y

echo "Installing curl ..."
sudo apt-get install curl -y

echo "Installing zip and unzip ..."
sudo apt-get install zip -y
sudo apt-get install unzip -y

echo "Installing vi and vim"
sudo apt-get install vim -y

echo "Installing robo3t..."
sudo snap install robo3t-snap

./installers/ui.sh
./installers/node_libraries.sh
./installers/gnome.sh
./installers/zsh.sh

./config_files.sh
