name: 'Dotfiles Install'
description: 'Run dotfiles installer script via curl'
inputs:
  run_as:
    description: 'User to run commands as (e.g., "ci" for containerized workflows)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Run curl installer (CI)
      env:
        RUN_AS: ${{ inputs.run_as }}
      shell: bash
      run: |
        if [ -n "$RUN_AS" ]; then
          su - $RUN_AS -c "
            curl -fsSL https://raw.githubusercontent.com/dantehemerson/.dotfiles/refs/heads/master/install.sh \
              | bash -s -- --ci
          "
        else
          curl -fsSL https://raw.githubusercontent.com/dantehemerson/.dotfiles/refs/heads/master/install.sh \
            | bash -s -- --ci
        fi
